services:
  user-app:
    image: aaditya999/wallet-userapp:latest
    container_name: user-app
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - PORT=${USER_APP_PORT}
    ports:
      - "3000:3000"
    depends_on:
      - mock-bank-service

  mock-bank-service:
    image: aaditya999/wallet-mockbank:latest
    container_name: mock-bank
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - BANK_WEBHOOK=${BANK_WEBHOOK}
      - PORT=${MOCK_BANK_PORT}
    ports:
      - "3001:3001"

  bank-webhook-service:
    image: aaditya999/wallet-bankwebhook:latest
    container_name: bank-webhook
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${BANK_WEBHOOK_PORT}

  # nginx:
  #   image: nginx:alpine
  #   container_name: wallet-nginx
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - /etc/letsencrypt:/etc/letsencrypt:ro
  #   depends_on:
  #     - user-app
  #     - merchant-app
  #     - express-api
